# Generated by Django 5.0.6 on 2025-10-31 18:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaperBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "strategy",
                    models.CharField(default="LLM_Consensus_Strategy", max_length=100),
                ),
                ("pair", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("stopped", "Stopped"),
                            ("error", "Error"),
                        ],
                        default="stopped",
                        max_length=20,
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2, default=10000.0, max_digits=15
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2, default=10000.0, max_digits=15
                    ),
                ),
                (
                    "total_profit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "position_size",
                    models.DecimalField(decimal_places=4, default=0.15, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_trade_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "paper_bots",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaperTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=10
                    ),
                ),
                ("pair", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "profit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "profit_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("consensus_decision", models.CharField(max_length=10)),
                (
                    "consensus_confidence",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("consensus_reasoning", models.TextField()),
                ("provider_votes", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="api.paperbot",
                    ),
                ),
            ],
            options={
                "db_table": "paper_trades",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PaperPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pair", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("entry_price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("entry_value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="api.paperbot",
                    ),
                ),
                (
                    "entry_trade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_position",
                        to="api.papertrade",
                    ),
                ),
            ],
            options={
                "db_table": "paper_positions",
                "ordering": ["-opened_at"],
                "unique_together": {("bot", "pair")},
            },
        ),
    ]
