# Generated by Django 5.0.6 on 2025-10-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperbot",
            name="auto_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paperbot",
            name="current_pair",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="paperbot",
            name="last_scan_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="paperbot",
            name="pair",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
